### ISSUE TITLE
'docker-compose-test-local.yml' unit doesn't work on windows

### ISSUE THREAD

**Issue by kht2199** [vfarcic/go-demo#1]
> this is my first issue in my life.
> and i'm not native english.
> sorry.

i installed docker toolbox on windows.
and made go-demo docker machine virtual driver.
i get sources from this git repository (thank you. that is very nice all things)
to my path ( e:/project/go-demo/... )

so, i did test by command ( docker-compose -f docker-compose-test-lcoal.yml run -d --rm unit ) 

and i typeed to get log info. but received massage about ' can't compile on path /usr/bin/myapp/. because not found source ' maybe. but that meaning.

so i did those commands in my linux Vagrant server only using 'docker-compose and docker' , but it works well.

i wonder why it didn't work on windows ( Docker quick terminal )
i love your all books. bye

**Comment by vfarcic** [comment]
Docker Machine mounts your local user's directory inside the machine. Any other directory on your host is not available inside the VM. Can you move the `go-demo` directory inside on of the directories that belong to your user and try again. I don't have access to Windows right now to confirm the path but it should be something like c:/users/[USER_NAME]/...

Can you please let me know whether it worked. If it didn't or you have any trouble locating your user's dir, please ping me on HangOuts (user: viktor@farcic.com) or Skype (user: vfarcic), and we'll take a look at it together.

**Comment by kht2199** [comment]
i didn't know and i had wondered, when i use docker-compose via docker-machine, where docker-compose's volume is pointing exactly. but i see now.

now i tested two case that you said about another workspace location.
**it works well** in my c:/users/[USER_NAME], as you said.
and i'll attach output.

![screenclip](https://cloud.githubusercontent.com/assets/13075105/19031056/dd2c4ada-898c-11e6-8243-0dd19445a538.png)

if you have any question to test windows environment another, please ask me. 
do i have to close my issue..?
