### ISSUE TITLE
go-demo can't connect to mongo db

### ISSUE THREAD

**Issue by rlaflamme** [vfarcic/go-demo#2]
Hi Viktor,
I am trying to setup my docker swarm based from the examples in The DevOps 2.1 Toolkit: Docker Swarm (excellent by the way!)

However when I create the go-demo service. the service failed:
 
[root@node1 ~]# docker logs 7148c0412577
panic: no reachable servers

goroutine 1 [running]:
panic(0x7b6480, 0xc8200c9be0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
main.setupDb()
        /usr/src/myapp/main.go:43 +0xc5
main.main()
        /usr/src/myapp/main.go:30 +0x14
[root@node1 ~]# docker ps -a

Here's my setup

[root@doc-machine ~]# docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
30b0diuj42e1xi8nb1f6dcrum    node2     Ready   Active
8birurzpi03fbsmobk72keui7    manager2  Ready   Active        Reachable
9cr88tkl4xtyosdee9mmwly6h *  manager1  Ready   Active        Leader
c53wp9ks0qcplme644v4m0zls    node3     Ready   Active
dp2n67k8cbtayqh8q3p1r9fjg    node1     Ready   Active

[root@node1 ~]# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
8bd68935c031        bridge              bridge              local
bb69ba346363        docker_gwbridge     bridge              local
3ekgvwum4aop        go-demo             overlay             swarm
131cd854ca31        host                host                local
9vyjyb8eci2q        ingress             overlay             swarm
ae35a08628f6        none                null                local

ID            NAME        REPLICAS  IMAGE                      COMMAND
2ay9q7t57zjm  proxy       1/1       vfarcic/docker-flow-proxy
7wpms6fjw3lo  go-demo-db  1/1       mongo:3.2.10
85dzs6wx7h2y  go-demo     0/1       vfarcic/go-demo:1.0
f2b6u7eqnr9o  util        global    alpine                     sleep 1000000000
[root@doc-machine ~]#

I can't figure out what is causing the issue

Thank's

Regards

Robert

**Comment by rlaflamme** [comment]
Here my configuration for go-demo and go-demo-db
[root@doc-machine ~]# docker service inspect go-demo --pretty
ID:             85dzs6wx7h2yauy616hfh5vvy
Name:           go-demo
Mode:           Replicated
 Replicas:      1
Placement:
UpdateConfig:
 Parallelism:   1
 On failure:    pause
ContainerSpec:
 Image:         vfarcic/go-demo:1.0
 Env:           DB=go-demo-db
Resources:
Networks: 3ekgvwum4aop2l2c13awecwjt 7a0ahahiommgvj8836e9jfnpl

[root@doc-machine ~]# docker service inspect go-demo-db --pretty
ID:             7wpms6fjw3loyjcpnmfzf5ubr
Name:           go-demo-db
Mode:           Replicated
 Replicas:      1
Placement:
UpdateConfig:
 Parallelism:   1
 On failure:    pause
ContainerSpec:
 Image:         mongo:3.2.10
Resources:
Networks: 3ekgvwum4aop2l2c13awecwjt

**Comment by rlaflamme** [comment]
GOTCHA!!!
Firewall issue!
centos 7 + vmware workstation + iptables active.
I flushed all firewall rules and now it is working.
Next I need to find the good rules to open to 27017
Regards
Robert

**Comment by vfarcic** [comment]
Cool. I love issues that close themselves :)

**Comment by rlaflamme** [comment]
Hi Victor
I finally succeeded your demo after configuring firewalld with theses rules below.

My  next steps: 
1) Finish the reading of the Devops 2.0 toolkit.
2) Buy the Devops 2.1 toolkit

Cheer and thanks!

Robert
(Devops for Loto-Quebec, Montreal. QC. Canada)

[root@node1 ~]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
INPUT_direct  all  --  anywhere             anywhere
INPUT_ZONES_SOURCE  all  --  anywhere             anywhere
INPUT_ZONES  all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
DOCKER-INGRESS  all  --  anywhere             anywhere
DOCKER-ISOLATION  all  --  anywhere             anywhere
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
FORWARD_direct  all  --  anywhere             anywhere
FORWARD_IN_ZONES_SOURCE  all  --  anywhere             anywhere
FORWARD_IN_ZONES  all  --  anywhere             anywhere
FORWARD_OUT_ZONES_SOURCE  all  --  anywhere             anywhere
FORWARD_OUT_ZONES  all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited
DROP       all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
OUTPUT_direct  all  --  anywhere             anywhere

Chain DOCKER (2 references)
target     prot opt source               destination

Chain DOCKER-INGRESS (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             state RELATED,ESTABLISHED tcp spt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:webcache
ACCEPT     tcp  --  anywhere             anywhere             state RELATED,ESTABLISHED tcp spt:webcache
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
ACCEPT     tcp  --  anywhere             anywhere             state RELATED,ESTABLISHED tcp spt:https
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain FORWARD_IN_ZONES (1 references)
target     prot opt source               destination
FWDI_public  all  --  anywhere             anywhere            [goto]
FWDI_public  all  --  anywhere             anywhere            [goto]

Chain FORWARD_IN_ZONES_SOURCE (1 references)
target     prot opt source               destination
FWDI_trusted  all  --  10.10.10.0/24        anywhere
FWDI_trusted  all  --  10.0.0.0/24          anywhere

Chain FORWARD_OUT_ZONES (1 references)
target     prot opt source               destination
FWDO_public  all  --  anywhere             anywhere            [goto]
FWDO_public  all  --  anywhere             anywhere            [goto]

Chain FORWARD_OUT_ZONES_SOURCE (1 references)
target     prot opt source               destination
FWDO_trusted  all  --  anywhere             10.10.10.0/24
FWDO_trusted  all  --  anywhere             10.0.0.0/24

Chain FORWARD_direct (1 references)
target     prot opt source               destination

Chain FWDI_public (2 references)
target     prot opt source               destination
FWDI_public_log  all  --  anywhere             anywhere
FWDI_public_deny  all  --  anywhere             anywhere
FWDI_public_allow  all  --  anywhere             anywhere
ACCEPT     icmp --  anywhere             anywhere

Chain FWDI_public_allow (1 references)
target     prot opt source               destination

Chain FWDI_public_deny (1 references)
target     prot opt source               destination

Chain FWDI_public_log (1 references)
target     prot opt source               destination

Chain FWDI_trusted (2 references)
target     prot opt source               destination
FWDI_trusted_log  all  --  anywhere             anywhere
FWDI_trusted_deny  all  --  anywhere             anywhere
FWDI_trusted_allow  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain FWDI_trusted_allow (1 references)
target     prot opt source               destination

Chain FWDI_trusted_deny (1 references)
target     prot opt source               destination

Chain FWDI_trusted_log (1 references)
target     prot opt source               destination

Chain FWDO_public (2 references)
target     prot opt source               destination
FWDO_public_log  all  --  anywhere             anywhere
FWDO_public_deny  all  --  anywhere             anywhere
FWDO_public_allow  all  --  anywhere             anywhere

Chain FWDO_public_allow (1 references)
target     prot opt source               destination

Chain FWDO_public_deny (1 references)
target     prot opt source               destination

Chain FWDO_public_log (1 references)
target     prot opt source               destination

Chain FWDO_trusted (2 references)
target     prot opt source               destination
FWDO_trusted_log  all  --  anywhere             anywhere
FWDO_trusted_deny  all  --  anywhere             anywhere
FWDO_trusted_allow  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain FWDO_trusted_allow (1 references)
target     prot opt source               destination

Chain FWDO_trusted_deny (1 references)
target     prot opt source               destination

Chain FWDO_trusted_log (1 references)
target     prot opt source               destination

Chain INPUT_ZONES (1 references)
target     prot opt source               destination
IN_public  all  --  anywhere             anywhere            [goto]
IN_public  all  --  anywhere             anywhere            [goto]

Chain INPUT_ZONES_SOURCE (1 references)
target     prot opt source               destination
IN_trusted  all  --  10.10.10.0/24        anywhere
IN_trusted  all  --  10.0.0.0/24          anywhere

Chain INPUT_direct (1 references)
target     prot opt source               destination

Chain IN_public (2 references)
target     prot opt source               destination
IN_public_log  all  --  anywhere             anywhere
IN_public_deny  all  --  anywhere             anywhere
IN_public_allow  all  --  anywhere             anywhere
ACCEPT     icmp --  anywhere             anywhere

Chain IN_public_allow (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:2376
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:27017
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:7946
ACCEPT     udp  --  anywhere             anywhere             udp dpt:7946
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:4789
ACCEPT     udp  --  anywhere             anywhere             udp dpt:4789
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh ctstate NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http ctstate NEW

Chain IN_public_deny (1 references)
target     prot opt source               destination

Chain IN_public_log (1 references)
target     prot opt source               destination

Chain IN_trusted (2 references)
target     prot opt source               destination
IN_trusted_log  all  --  anywhere             anywhere
IN_trusted_deny  all  --  anywhere             anywhere
IN_trusted_allow  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain IN_trusted_allow (1 references)
target     prot opt source               destination

Chain IN_trusted_deny (1 references)
target     prot opt source               destination

Chain IN_trusted_log (1 references)
target     prot opt source               destination

Chain OUTPUT_direct (1 references)
target     prot opt source               destination
[root@node1 ~]#
